dist: trusty
sudo: required
language: node_js
node_js:
  - "12.7.0"
cache:
  directories:
    - node_modules
    - ~/.npm
branches:
  except:
    - master
install:
  - npm ci
  - npm run export
deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: develop